WorkoutTracker/Controllers/ExerciseController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WorkoutTracker.Data.Models;
using WorkoutTracker.Services.IService;
using WorkoutTracker.Models;

namespace WorkoutTracker.Controllers
{
    public class ExerciseController : Controller
    {

        private IExerciseService _exerciseService;
        private IWorkoutService _workoutService;
        public ExerciseController(IWorkoutService workoutService, IExerciseService exerciseService)
        {

            _exerciseService = exerciseService;
            _workoutService = workoutService;

        }
        // GET: ExerciseController
        public ActionResult Index()
        {
            return View();
        }

        // GET: ExerciseController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ExerciseController/Create
        public ActionResult Create(int ID)
        {
            Workout workout = _workoutService.GetWorkout(ID);
            ExerciseWorkout exerciseWorkout = new ExerciseWorkout()
            {
                Workout = ID,
                WorkoutName = workout.Name
            };
            return View(exerciseWorkout);
        }

        // POST: ExerciseController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExerciseWorkout exerciseWorkout)
        {
            try
            {
                Exercise exercise = new Exercise()
                {
                    Name = exerciseWorkout.ExerciseName,
                };
                _exerciseService.AddExerciseToWorkout(exerciseWorkout.Workout, exercise);
                return RedirectToAction("Details", "Workout", new { ID = exerciseWorkout.Workout });
            }
            catch
            {
                return View();
            }
        }

        // GET: ExerciseController/Edit/5
        public ActionResult Edit(int id)
        {
            Exercise exercise = _exerciseService.GetExercise(id);
            IList<Workout> workouts = _workoutService.GetWorkouts();

            ExerciseWorkout exerciseWorkout = new ExerciseWorkout();
            foreach (var workout in workouts)
            {
                foreach (var e in workout.Exercises)
                {
                    if (e.ID == exercise.ID)
                    {
                        exerciseWorkout.ExerciseName = exercise.Name;
                        exerciseWorkout.ID = exercise.ID;
                        exerciseWorkout.Workout = workout.ID;
                    }
                }
            }

            return View(exerciseWorkout);
        }

        // POST: ExerciseController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ExerciseWorkout exerciseWorkout)
        {
            try
            {
                Exercise exercise = new Exercise()
                {
                    ID = exerciseWorkout.ID,
                    Name = exerciseWorkout.ExerciseName,

                };
                _exerciseService.UpdateExercise(exercise);
                return RedirectToAction("Details", "Workout", new { ID = exerciseWorkout.Workout });
            }
            catch
            {
                return View();
            }
        }

        // GET: ExerciseController/Delete/5
        public ActionResult Delete(int id)
        {
            Exercise exercise = _exerciseService.GetExercise(id);
            IList<Workout> workouts = _workoutService.GetWorkouts();

            ExerciseWorkout exerciseWorkout = new ExerciseWorkout();
            foreach (var workout in workouts)
            {
                foreach (var e in workout.Exercises)
                {
                    if (e.ID == exercise.ID)
                    {
                        exerciseWorkout.ExerciseName = exercise.Name;
                        exerciseWorkout.ID = exercise.ID;
                        exerciseWorkout.Workout = workout.ID;
                    }
                }
            }

            return View(exerciseWorkout);
        }

        // POST: ExerciseController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ExerciseWorkout exerciseWorkout)
        {
            try
            {

                _exerciseService.RemoveExercise(exerciseWorkout.ID);
                return RedirectToAction("Details", "Workout", new { ID = exerciseWorkout.Workout });
            }
            catch
            {
                return View();
            }
        }
    }
}

WorkoutTracker/Controllers/SetController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WorkoutTracker.Data.Models;
using WorkoutTracker.Models;
using WorkoutTracker.Services.IService;

namespace WorkoutTracker.Controllers
{
    public class SetController : Controller
    {
        private ISetService _setService;
        private IExerciseService _exerciseService;
        private readonly IWorkoutService _workoutService;
        public SetController(ISetService setService, IExerciseService exerciseService, IWorkoutService workoutService)
        {
            _exerciseService = exerciseService;
            _setService = setService;
            _workoutService = workoutService;

        }
        // GET: SetController
        public ActionResult Index()
        {
            return View();
        }

        // GET: SetController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SetController/Create
        public ActionResult Create(int ID)
        {

            IList<Workout> workouts = _workoutService.GetWorkouts();
            Exercise exercise = _exerciseService.GetExercise(ID);
            int workoutID = new int();
            foreach (var workout in workouts)
            {
                if (workout.Exercises.Contains(exercise))
                {
                    workoutID = workout.ID;
                }
            }




            ExerciseSet exerciseSet = new ExerciseSet()
            {
                ExerciseID = exercise.ID,
                ExerciseName = exercise.Name,
                WorkoutID = workoutID
            };






            return View(exerciseSet);
        }

        // POST: SetController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExerciseSet exerciseSet)
        {
            try
            {
                Set set = new Set()
                {
                    Reps = exerciseSet.Reps,
                    Weight = exerciseSet.Weight,

                };

                _setService.AddSetToExercise(exerciseSet.ExerciseID, set);
                return RedirectToAction("Details", "Workout", new { ID = exerciseSet.WorkoutID });
            }
            catch
            {
                return View();
            }
        }

        // GET: SetController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SetController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SetController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SetController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WorkoutTracker/Controllers/WorkoutController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WorkoutTracker.Services.IService;
using WorkoutTracker.Models;
using WorkoutTracker.Data.Models;

namespace WorkoutTracker.Controllers
{
    public class WorkoutController : Controller
    {
        private IWorkoutService _workoutService;
        private IExerciseService _exerciseService;
        private IUserService _userService;
        public WorkoutController(IWorkoutService workoutService, IExerciseService exerciseService, IUserService userService)
        {
            _workoutService = workoutService;
            _exerciseService = exerciseService;
            _userService = userService;

        }
        // GET: WorkoutController
        public ActionResult Index()
        {
            var workouts = _workoutService.GetWorkouts();
            return View(workouts);
        }
        public ActionResult MyWorkouts(int ID)
        {
            var workouts = _workoutService.GetWorkoutsUser(ID);
            return View(workouts);
        }

        // GET: WorkoutController/Details/5
        public ActionResult Details(int id)
        {
            var workout = _workoutService.GetWorkout(id);


            return View(workout);
        }

        // GET: WorkoutController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WorkoutController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Workout workout)
        {
            try
            {


                User user = _userService.GetUser((int)HttpContext.Session.GetInt32("UserID"));
                _workoutService.AddWorkoutUser(user, workout);
                return RedirectToAction("MyWorkouts", new { ID = HttpContext.Session.GetInt32("UserID") });
            }
            catch
            {
                return View();
            }
        }

        // GET: WorkoutController/Edit/5
        public ActionResult Edit(int id)
        {
            var workout = _workoutService.GetWorkout(id);
            return View(workout);
        }

        // POST: WorkoutController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Workout workout)
        {
            try
            {

                _workoutService.UpdateWorkout(workout);
                return RedirectToAction("MyWorkouts", new { ID = HttpContext.Session.GetInt32("UserID") });
            }
            catch
            {
                return View();
            }
        }

        // GET: WorkoutController/Delete/5
        public ActionResult Delete(int id)
        {
            var workout = _workoutService.GetWorkout(id);
            return View(workout);
        }

        // POST: WorkoutController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _workoutService.DeleteWorkout(id);
                return RedirectToAction("MyWorkouts", new { ID = HttpContext.Session.GetInt32("UserID") });
            }
            catch
            {
                return View();
            }
        }
    }
}

WorkoutTracker/Views/Workout/Create.cshtml
@model WorkoutTracker.Data.Models.Workout
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Workout</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-warning" asp-action="MyWorkouts" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetInt32("UserID")">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WorkoutTracker/Views/Workout/Delete.cshtml
@model WorkoutTracker.Data.Models.Workout
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Workout</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="MyWorkouts" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetInt32("UserID")">Back to List</a>
    </form>
</div>

WorkoutTracker/Views/Workout/Details.cshtml
@model WorkoutTracker.Data.Models.Workout
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Details";
}

<div>
    <h2>Workout: @Model.Name</h2>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>

    <br />
    <div class="container w-100">
        <div class="row">
            <div class="col d-flex align-items-center justify-content-center">
                <h2>@Html.DisplayNameFor(model => model.Exercises)</h2>
            </div>
            <div class="col d-flex align-items-center justify-content-center">
                <a class="btn btn-secondary" asp-controller="Exercise" asp-action="Create" asp-route-id="@Model.ID">Add Exercise</a>
            </div>
        </div>
    </div>


    @foreach (var exercise in Model.Exercises)
    {
        <div class="container p-2 my-3 card">
            <div class="row my-2">
                <div class="col font-weight-bold justify-content-center align-content-center">
                    @exercise.Name
                </div>
                <div class="col d-flex justify-content-around">
                    <a class="btn btn-info" asp-action="Edit" asp-controller="Exercise" asp-route-id="@exercise.ID">Edit Exercise</a>
                    <br />
                    <a class="btn btn-danger" asp-action="Delete" asp-controller="Exercise" asp-route-id="@exercise.ID">Delete Exercise</a>
                    <br />
                </div>
                <div class="col d-flex justify-content-center">
                    <a class="btn btn-success" asp-action="Create" asp-controller="Set" asp-route-id="@exercise.ID">Add Set</a>
                </div>
            </div>
            <br />
            <table class="table table-striped card-body">
                <tr class="col-sm-2">
                    <th>
                        Weight
                    </th>
                    <th>
                        Reps
                    </th>
                </tr>
                @foreach (var set in exercise.Sets)
                {

                    <tr class="col-sm-10">
                        <td>
                            @set.Weight
                        </td>
                        <td>
                            @set.Reps
                        </td>
                    </tr>
                }
            </table>

        </div>


    }




</div>
<div>
    <a asp-action="MyWorkouts" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetInt32("UserID")">Back to List</a>
</div>

WorkoutTracker/Views/Workout/Edit.cshtml
@model WorkoutTracker.Data.Models.Workout
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Workout</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="MyWorkouts" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetInt32("UserID")">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WorkoutTracker/Views/Workout/Index.cshtml
@model IEnumerable<WorkoutTracker.Data.Models.Workout>

@{
    ViewData["Title"] = "Index";
}

<h1>Your Workouts</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WorkoutTracker/Views/Workout/MyWorkouts.cshtml
@model IEnumerable<WorkoutTracker.Data.Models.Workout>

@{
    ViewData["Title"] = "MyWorkouts";
}

<h1>MyWorkouts</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>