WorkoutTracker/Controllers/WorkoutController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WorkoutTracker.Services.IService;
using WorkoutTracker.Models;
using WorkoutTracker.Data.Models;

namespace WorkoutTracker.Controllers
{
    public class WorkoutController : Controller
    {
        private IWorkoutService _workoutService;
        private IExerciseService _exerciseService;
        private IUserService _userService;
        public WorkoutController(IWorkoutService workoutService, IExerciseService exerciseService, IUserService userService)
        {
            _workoutService = workoutService;
            _exerciseService = exerciseService;
            _userService = userService;

        }
        // GET: WorkoutController
        public ActionResult Index()
        {
            var workouts = _workoutService.GetWorkouts();
            return View(workouts);
        }
        public ActionResult MyWorkouts(int ID)
        {
            var workouts = _workoutService.GetWorkoutsUser(ID);
            return View(workouts);
        }

        // GET: WorkoutController/Details/5
        public ActionResult Details(int id)
        {
            var workout = _workoutService.GetWorkout(id);


            return View(workout);
        }

        // GET: WorkoutController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WorkoutController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Workout workout)
        {
            try
            {


                User user = _userService.GetUser((int)HttpContext.Session.GetInt32("UserID"));
                _workoutService.AddWorkoutUser(user, workout);
                return RedirectToAction("MyWorkouts", new { ID = HttpContext.Session.GetInt32("UserID") });
            }
            catch
            {
                return View();
            }
        }

        // GET: WorkoutController/Edit/5
        public ActionResult Edit(int id)
        {
            var workout = _workoutService.GetWorkout(id);
            return View(workout);
        }

        // POST: WorkoutController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Workout workout)
        {
            try
            {

                _workoutService.UpdateWorkout(workout);
                return RedirectToAction("MyWorkouts", new { ID = HttpContext.Session.GetInt32("UserID") });
            }
            catch
            {
                return View();
            }
        }

        // GET: WorkoutController/Delete/5
        public ActionResult Delete(int id)
        {
            var workout = _workoutService.GetWorkout(id);
            return View(workout);
        }

        // POST: WorkoutController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _workoutService.DeleteWorkout(id);
                return RedirectToAction("MyWorkouts", new { ID = HttpContext.Session.GetInt32("UserID") });
            }
            catch
            {
                return View();
            }
        }
    }
}

WorkoutTracker/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkoutTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @{
                    if (HttpContextAccessor.HttpContext.Session.GetInt32("UserID") != null)
                    {
                        <a class="navbar-brand" asp-area="" asp-controller="Workout" asp-action="MyWorkouts" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetInt32("UserID")">WorkoutTracker</a>
                    }
                    else
                    { <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">WorkoutTracker</a>}

                }
                @*<a class="navbar-brand" asp-area="" asp-controller="Workout">WorkoutTracker</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WorkoutTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>